# Generated by Django 3.1.2 on 2021-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRetiro',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_cl', models.CharField(max_length=100)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('horario_ret', models.TimeField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
