# Generated by Django 3.1.2 on 2021-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRetiro',
            fields=[
                ('num_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('nombre_cl', models.CharField(max_length=100)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
