# Generated by Django 3.1.2 on 2021-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRetiro',
            fields=[
                ('num_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nombre_cl', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('num_telf', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_pro', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=100)),
                ('estado_orden', models.CharField(blank=True, default='Pendiente', max_length=100)),
            ],
        ),
    ]
