# Generated by Django 3.1.2 on 2021-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenretiro',
            name='estado_orden',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
