# Generated by Django 3.1.2 on 2021-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenretiro',
            name='nombre_pro',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ordenretiro',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
